parameters:
  ongr_api.data_request.class: ONGR\ApiBundle\Service\DataRequestService
  router.class: ONGR\ApiBundle\Routing\Router


#  ongr_api.api.[version].[endpoint].controller
#  ongr_api.api.[version].[endpoint].data_request
#  ongr_api.api.[version].[endpoint].router
